import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Button from '../../components/button';
import MainContainer from '../../components/MainContainer';
import { useJokeModel } from '../../models/joke/useJokeModel';

interface PageProps {
  joke: string;
}

const Joke: NextPage<PageProps> = ({ joke }) => {
  const { view } = useJokeModel();
  const {query} = useRouter()

  return (
    <div>
      <Head>
        <title>Joke Type</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <div>
          <h3 style={{ textAlign: 'center' }}>{view?.joke}</h3>
          <Button onClick={() => view.handleGetSingleJoke(query?.joke as string)}>Show Joke</Button>
        </div>
      </MainContainer>
    </div>
  );
};

export default Joke;
