import type { NextPage, NextPageContext } from 'next';
import Head from 'next/head';
import Button from '../../components/button';
import MainContainer from '../../components/MainContainer';


const asyncPipe =
  (...fns: any[]) =>
    (x: any) =>
      fns.reduce(async (f, y) => y(await f), x);

const toJson = (response: Response) => response.json();

const request = asyncPipe(fetch, toJson);


interface PageProps {
  joke: string;
}

const Joke: NextPage<PageProps> = ({ joke }) => {

  return (
    <div>
      <Head>
        <title>Joke Type</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <div>
          <h3 style={{ textAlign: 'center' }}>{joke}</h3>
          <Button>Show Joke</Button>
        </div>
      </MainContainer>
    </div>
  );
};

export async function getServerSideProps(params: NextPageContext) {
  const { query } = params

  const type = await request(`https://v2.jokeapi.dev/joke/${query.type}?type=single`);

  console.log("type",type)

  return {
    props: { joke: type.joke }
  }
}

export default Joke;
