import type { NextPage } from 'next';
import Head from 'next/head';
import Button from '../components/button';
import FlexContainer from '../components/FlexContainer';
import MainContainer from '../components/MainContainer';

const Home: NextPage = () => {
  const JokeTypes = [
    'Programming',
    'Misc',
    'Dark',
    'Pun',
    'Spooky',
    'Christmas',
  ];

  return (
    <div>
      <Head>
        <title>Joke App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <div>
          <h3 style={{ textAlign: 'center' }}>Welcome to Joke web</h3>
          <p style={{ textAlign: 'center', color: "#0000005e" }}>Select Joke type to begin</p>
          <FlexContainer>
          {JokeTypes.map(joketype => (
            <Button>{joketype}</Button>
          ))}
          </FlexContainer>
          <Button>Begin Process</Button>
        </div>
      </MainContainer>
    </div>
  );
};

export default Home;
