import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import Button, { SubmitButton } from '../components/button';
import FlexContainer from '../components/FlexContainer';
import MainContainer from '../components/MainContainer';

const Home: NextPage = () => {
  const JokeTypes = [
    'Programming',
    'Miscellaneous',
    'Dark',
    'Pun',
    'Spooky',
    'Christmas',
  ];

  const [joke, setjoke] = useState<string>();

  return (
    <div>
      <Head>
        <title>Joke App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <div>
          <h3 style={{ textAlign: 'center' }}>Welcome to Joke web</h3>
          {
            joke === undefined ?
              <p style={{ textAlign: 'center', color: "#0000005e" }}>Select Joke type to begin</p>
              :
              <p style={{ textAlign: 'center', color: "#0000005e" }}>Selected <b>"{joke}"</b></p>
          }
          <FlexContainer>
            {JokeTypes.map(joketype => (
              <Button onClick={() => setjoke(joketype)}>{joketype}</Button>
            ))}
            <Link href={`/joke/${joke}`}><SubmitButton >Get Joke</SubmitButton></Link>
          </FlexContainer>
        </div>
      </MainContainer>
    </div>
  );
};

export default Home;
